#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 30, 2019 07:58:35 PM IST  platform: Windows NT

import sys
import sqlite3 as sq
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import admin_users_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = users_detail(root)
    admin_users_support.init(root, top)
    root.mainloop()


w = None


def create_users_detail(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = users_detail(w)
    admin_users_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_users_detail():
    global w
    w.destroy()
    w = None


class users_detail:
    def selected_item(self):
        curItem = self.users_tree.focus()
        contents = (self.users_tree.item(curItem))
        email = contents['values'][0]
        conn = sq.connect('accounts.db')
        conn.execute("INSERT INTO FRAUDS (email) VALUES (?)", (email,))
        conn.execute("DELETE FROM ACCOUNT_DETAILS WHERE email=(?)", (email,))
        conn.commit()
        messagebox.showinfo("Message", "User successfully put into frauds list")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=
        [('selected', _compcolor), ('active', _ana2color)])

        top.geometry("682x595+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Manage Users")
        top.configure(background="#d9d9d9")

        self.style.configure('Treeview', font="TkDefaultFont")
        self.users_tree = ScrolledTreeView(top)
        self.users_tree.place(relx=0.0, rely=0.134, relheight=0.886
                              , relwidth=0.997)
        self.users_tree.configure(
            columns=("Col1", "Col2"))
        # build_treeview_support starting.
        self.users_tree.heading("#0", text="")
        self.users_tree.heading("#0", anchor="center")
        self.users_tree.column("#0", width="0")
        self.users_tree.column("#0", minwidth="0")
        self.users_tree.column("#0", stretch="1")
        self.users_tree.column("#0", anchor="w")

        self.users_tree.heading("Col1", text="Email Id")
        self.users_tree.heading("Col1", anchor="center")
        self.users_tree.column("Col1", width="329")
        self.users_tree.column("Col1", minwidth="20")
        self.users_tree.column("Col1", stretch="1")
        self.users_tree.column("Col1", anchor="center")

        self.users_tree.heading("Col2", text="Count")
        self.users_tree.heading("Col2", anchor="center")
        self.users_tree.column("Col2", width="329")
        self.users_tree.column("Col2", minwidth="20")
        self.users_tree.column("Col2", stretch="1")
        self.users_tree.column("Col2", anchor="center")

        conn = sq.connect('accounts.db')
        all_rows = conn.execute("SELECT * from COUNT")
        for row in all_rows:
            self.users_tree.insert('', 'end', values=(
                row[0], row[1]))

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=-0.117, rely=0.067, height=36, width=332)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''privileges on users''')

        self.block_button = tk.Button(top)
        self.block_button.place(relx=0.806, rely=0.067, height=33, width=87)
        self.block_button.configure(activebackground="#ececec")
        self.block_button.configure(activeforeground="#000000")
        self.block_button.configure(background="#d9d9d9")
        self.block_button.configure(disabledforeground="#a3a3a3")
        self.block_button.configure(foreground="#000000")
        self.block_button.configure(highlightbackground="#d9d9d9")
        self.block_button.configure(highlightcolor="black")
        self.block_button.configure(pady="0")
        self.block_button.configure(text='''Block Users''')
        self.block_button.configure(command=self.selected_item)


# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        # self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                      | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                      + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''

        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)

        return wrapped

    def __str__(self):
        return str(self.master)


def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''

    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)

    return wrapped


class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''

    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)


import platform


def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))


def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')


def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1 * int(event.delta / 120), 'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1 * int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')


def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1 * int(event.delta / 120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1 * int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')


if __name__ == '__main__':
    vp_start_gui()
