#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 30, 2019 10:15:54 PM IST  platform: Windows NT

import Bill_generation as bill
import admin_users as us
import cat_priv as cat
import items as it

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import admin_piri_support


def vp_start_gui():
    """Starting point when module is the main routine."""
    global val, w, root
    root = tk.Tk()
    top = admin_privileges(root)
    admin_piri_support.init(root, top)
    root.mainloop()


w = None


def create_admin_privileges(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = admin_privileges(w)
    admin_piri_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_admin_privileges():
    global w
    w.destroy()
    w = None


def open_items():
    it.create_item_window(root=root)


def open_users():
    us.create_users_detail(root=root)


def open_categories():
    cat.create_cat_window(root=root)


def generate_bills():
    bill.create_bill_generation_window(root=root)


class admin_privileges:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("600x450+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Admin Privileges")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.233, rely=0.111, height=26, width=317)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Welcome Admin''')

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.users_button = tk.Button(top)
        self.users_button.place(relx=0.233, rely=0.311, height=53, width=306)
        self.users_button.configure(activebackground="#ececec")
        self.users_button.configure(activeforeground="#000000")
        self.users_button.configure(background="#d9d9d9")
        self.users_button.configure(disabledforeground="#a3a3a3")
        self.users_button.configure(foreground="#000000")
        self.users_button.configure(highlightbackground="#d9d9d9")
        self.users_button.configure(highlightcolor="black")
        self.users_button.configure(pady="0")
        self.users_button.configure(text='''Users''')
        self.users_button.configure(command=open_users)

        self.items_button = tk.Button(top)
        self.items_button.place(relx=0.233, rely=0.467, height=53, width=308)
        self.items_button.configure(activebackground="#ececec")
        self.items_button.configure(activeforeground="#000000")
        self.items_button.configure(background="#d9d9d9")
        self.items_button.configure(disabledforeground="#a3a3a3")
        self.items_button.configure(foreground="#000000")
        self.items_button.configure(highlightbackground="#d9d9d9")
        self.items_button.configure(highlightcolor="black")
        self.items_button.configure(pady="0")
        self.items_button.configure(text='''Items''')
        self.items_button.configure(command=open_items)

        self.category_privileges = tk.Button(top)
        self.category_privileges.place(relx=0.233, rely=0.622, height=43
                                       , width=313)
        self.category_privileges.configure(activebackground="#ececec")
        self.category_privileges.configure(activeforeground="#000000")
        self.category_privileges.configure(background="#d9d9d9")
        self.category_privileges.configure(disabledforeground="#a3a3a3")
        self.category_privileges.configure(foreground="#000000")
        self.category_privileges.configure(highlightbackground="#d9d9d9")
        self.category_privileges.configure(highlightcolor="black")
        self.category_privileges.configure(pady="0")
        self.category_privileges.configure(text='''Categories''')
        self.category_privileges.configure(command=open_categories)

        self.bill_generation_button = tk.Button(top)
        self.bill_generation_button.place(relx=0.233, rely=0.756, height=43
                                          , width=313)
        self.bill_generation_button.configure(activebackground="#ececec")
        self.bill_generation_button.configure(activeforeground="#000000")
        self.bill_generation_button.configure(background="#d9d9d9")
        self.bill_generation_button.configure(disabledforeground="#a3a3a3")
        self.bill_generation_button.configure(foreground="#000000")
        self.bill_generation_button.configure(highlightbackground="#d9d9d9")
        self.bill_generation_button.configure(highlightcolor="black")
        self.bill_generation_button.configure(pady="0")
        self.bill_generation_button.configure(text='''Bill generation''')
        self.bill_generation_button.configure(command=generate_bills)


if __name__ == '__main__':
    vp_start_gui()
