#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 01, 2019 02:12:20 AM IST  platform: Windows NT

import sys
import create_cat as cc
import del_cat as dc
import merge_cat as mc

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import cat_priv_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = cat_window(root)
    cat_priv_support.init(root, top)
    root.mainloop()


w = None


def create_cat_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = cat_window(w)
    cat_priv_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_cat_window():
    global w
    w.destroy()
    w = None


class cat_window:
    def createcat(self):
        cc.vp_start_gui()

    def deletecat(self):
        dc.vp_start_gui()

    def mergecat(self):
        mc.vp_start_gui()

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("600x158+589+247")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Category Privileges")
        top.configure(background="#d9d9d9")

        self.create_cat_button = tk.Button(top)
        self.create_cat_button.place(relx=0.067, rely=0.38, height=33, width=148)

        self.create_cat_button.configure(activebackground="#ececec")
        self.create_cat_button.configure(activeforeground="#000000")
        self.create_cat_button.configure(background="#d9d9d9")
        self.create_cat_button.configure(disabledforeground="#a3a3a3")
        self.create_cat_button.configure(foreground="#000000")
        self.create_cat_button.configure(highlightbackground="#d9d9d9")
        self.create_cat_button.configure(highlightcolor="black")
        self.create_cat_button.configure(pady="0")
        self.create_cat_button.configure(text='''Create new category''')
        self.create_cat_button.configure(command=self.createcat)

        self.delete_cat_button = tk.Button(top)
        self.delete_cat_button.place(relx=0.417, rely=0.38, height=33, width=130)

        self.delete_cat_button.configure(activebackground="#ececec")
        self.delete_cat_button.configure(activeforeground="#000000")
        self.delete_cat_button.configure(background="#d9d9d9")
        self.delete_cat_button.configure(disabledforeground="#a3a3a3")
        self.delete_cat_button.configure(foreground="#000000")
        self.delete_cat_button.configure(highlightbackground="#d9d9d9")
        self.delete_cat_button.configure(highlightcolor="black")
        self.delete_cat_button.configure(pady="0")
        self.delete_cat_button.configure(text='''Delete a category''')
        self.delete_cat_button.configure(command=self.deletecat)

        self.merge_cat_button = tk.Button(top)
        self.merge_cat_button.place(relx=0.717, rely=0.38, height=33, width=142)
        self.merge_cat_button.configure(activebackground="#ececec")
        self.merge_cat_button.configure(activeforeground="#000000")
        self.merge_cat_button.configure(background="#d9d9d9")
        self.merge_cat_button.configure(disabledforeground="#a3a3a3")
        self.merge_cat_button.configure(foreground="#000000")
        self.merge_cat_button.configure(highlightbackground="#d9d9d9")
        self.merge_cat_button.configure(highlightcolor="black")
        self.merge_cat_button.configure(pady="0")
        self.merge_cat_button.configure(text='''Merge 2 Categories''')
        self.merge_cat_button.configure(command=self.mergecat)


if __name__ == '__main__':
    vp_start_gui()
