#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 01, 2019 01:52:51 AM IST  platform: Windows NT

import sys
import sqlite3 as sq
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import create_cat_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = newcat_window(root)
    create_cat_support.init(root, top)
    root.mainloop()


w = None


def create_newcat_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = newcat_window(w)
    create_cat_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_newcat_window():
    global w
    w.destroy()
    w = None


class newcat_window:
    def createcat(self):
        cat_text = str(self.new_cat_entry.get())
        conn = sq.connect('accounts.db')
        conn.execute("INSERT INTO CATEGORIES (category) \
                              VALUES (?)", (cat_text,))
        conn.commit()
        messagebox.showinfo("Message", "Category created")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("600x450+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Category")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.217, rely=0.356, height=26, width=100)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''New Category''')

        self.new_cat_entry = tk.Entry(top)
        self.new_cat_entry.place(relx=0.483, rely=0.356, height=24
                                 , relwidth=0.34)
        self.new_cat_entry.configure(background="white")
        self.new_cat_entry.configure(disabledforeground="#a3a3a3")
        self.new_cat_entry.configure(font="TkFixedFont")
        self.new_cat_entry.configure(foreground="#000000")
        self.new_cat_entry.configure(insertbackground="black")

        self.submit_button = tk.Button(top)
        self.submit_button.place(relx=0.433, rely=0.578, height=33, width=59)
        self.submit_button.configure(activebackground="#ececec")
        self.submit_button.configure(activeforeground="#000000")
        self.submit_button.configure(background="#d9d9d9")
        self.submit_button.configure(disabledforeground="#a3a3a3")
        self.submit_button.configure(foreground="#000000")
        self.submit_button.configure(highlightbackground="#d9d9d9")
        self.submit_button.configure(highlightcolor="black")
        self.submit_button.configure(pady="0")
        self.submit_button.configure(text='''Submit''')
        self.submit_button.configure(command=self.createcat)


if __name__ == '__main__':
    vp_start_gui()
