#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Dec 01, 2019 02:17:04 AM IST  platform: Windows NT

import sys
import sqlite3 as sq
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import del_cat_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = del_window(root)
    del_cat_support.init(root, top)
    root.mainloop()


w = None


def create_del_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = del_window(w)
    del_cat_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_del_window():
    global w
    w.destroy()
    w = None


class del_window:
    def deletecat(self):
        cat_text = str(self.delete_cat_entry.get())
        conn = sq.connect('accounts.db')
        query = conn.execute("SELECT * FROM CATEGORIES WHERE category=(?)", (cat_text,)).fetchone()[0]
        if query is not None:
            conn.execute("DELETE FROM CATEGORIES WHERE category=(?)", (cat_text,))
            conn.commit()
            messagebox.showinfo("Message", "Category deleted")
        else:
            messagebox.showerror("Message", "Entered category name does not exists")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("600x450+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Delete Category")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.083, rely=0.356, height=26, width=209)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Enter Category name to delete''')

        self.delete_cat_entry = tk.Entry(top)
        self.delete_cat_entry.place(relx=0.5, rely=0.356, height=24
                                    , relwidth=0.34)
        self.delete_cat_entry.configure(background="white")
        self.delete_cat_entry.configure(disabledforeground="#a3a3a3")
        self.delete_cat_entry.configure(font="TkFixedFont")
        self.delete_cat_entry.configure(foreground="#000000")
        self.delete_cat_entry.configure(insertbackground="black")

        self.submit_button = tk.Button(top)
        self.submit_button.place(relx=0.433, rely=0.556, height=33, width=59)
        self.submit_button.configure(activebackground="#ececec")
        self.submit_button.configure(activeforeground="#000000")
        self.submit_button.configure(background="#d9d9d9")
        self.submit_button.configure(disabledforeground="#a3a3a3")
        self.submit_button.configure(foreground="#000000")
        self.submit_button.configure(highlightbackground="#d9d9d9")
        self.submit_button.configure(highlightcolor="black")
        self.submit_button.configure(pady="0")
        self.submit_button.configure(text='''Submit''')
        self.submit_button.configure(command=self.deletecat)


if __name__ == '__main__':
    vp_start_gui()
